const fs = require('fs');
const path = require('path');

// Determine file paths
const jsonPath = path.join(__dirname, 'color-tokens.json');
const cssPath = path.join(__dirname, 'design-tokens.css');

// Read and parse design tokens JSON
if (!fs.existsSync(jsonPath)) {
  console.error(`Error: ${jsonPath} does not exist.`);
  process.exit(1);
}

const rawData = fs.readFileSync(jsonPath, 'utf8');
const tokens = JSON.parse(rawData);

/**
 * Generate a descriptive name for an HSL color based on its components.
 * Matches hues to color families and names lightness shades.
 */
function getUniqueName(h, s, l) {
  if (l === 100) return 'white';
  if (l === 0) return 'black';

  let baseName = '';
  if (s < 10) {
    baseName = 'neutral';
  } else {
    if (h < 15 || h >= 345) baseName = 'red';
    else if (h >= 15 && h < 45) baseName = 'orange';
    else if (h >= 45 && h < 75) baseName = 'yellow';
    else if (h >= 75 && h < 165) baseName = 'green';
    else if (h >= 165 && h < 195) baseName = 'cyan';
    else if (h >= 195 && h < 240) baseName = 'blue';
    else if (h >= 240 && h < 255) baseName = 'indigo';
    else if (h >= 255 && h < 285) baseName = 'violet';
    else if (h >= 285 && h < 315) baseName = 'magenta';
    else if (h >= 315 && h < 345) baseName = 'pink';
  }
  return `${baseName}-${l}`;
}

// 1. Collect all unique color values to build a primitive color palette
const uniqueHsls = new Set();
if (tokens.color) {
  if (tokens.color.light) {
    Object.values(tokens.color.light).forEach(val => uniqueHsls.add(val));
  }
  if (tokens.color.dark) {
    Object.values(tokens.color.dark).forEach(val => uniqueHsls.add(val));
  }
}

const nameGroups = {};
const hslToVarMap = {};

for (const hsl of uniqueHsls) {
  const match = hsl.match(/hsl\(\s*(\d+)\s*,\s*(\d+)%\s*,\s*(\d+)%\s*\)/);
  if (!match) {
    // If it's a non-standard color definition, sanitize it to a standard variable name
    const sanitized = hsl.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();
    hslToVarMap[hsl] = `--color-primitive-${sanitized}`;
    continue;
  }
  
  const h = parseInt(match[1]);
  const s = parseInt(match[2]);
  const l = parseInt(match[3]);
  
  const baseName = getUniqueName(h, s, l);
  if (!nameGroups[baseName]) {
    nameGroups[baseName] = [];
  }
  nameGroups[baseName].push({ hsl, h, s, l });
}

// Resolve duplicate names by appending a suffix index for collisions
for (const baseName in nameGroups) {
  const group = nameGroups[baseName];
  if (group.length === 1) {
    hslToVarMap[group[0].hsl] = `--color-primitive-${baseName}`;
  } else {
    // Sort items inside group deterministically by hue then saturation
    group.sort((a, b) => a.h - b.h || a.s - b.s);
    group.forEach((item, index) => {
      hslToVarMap[item.hsl] = `--color-primitive-${baseName}-${index + 1}`;
    });
  }
}

// 2. Build CSS output
let cssContent = `/* 
  THIS FILE IS AUTO-GENERATED BY convert-tokens.js.
  DO NOT EDIT DIRECTLY.
*/

:root {
  /* ==========================================================================
     PRIMITIVE COLORS
     ========================================================================== */
`;

// Sort and output the primitive color variables
const sortedPrimitives = Object.entries(hslToVarMap).sort((a, b) => a[1].localeCompare(b[1]));
for (const [hsl, varName] of sortedPrimitives) {
  cssContent += `  ${varName}: ${hsl};\n`;
}

cssContent += `
  /* ==========================================================================
     NON-COLOR TOKENS
     ========================================================================== */
`;

// Map other categories directly into :root
const categories = ['typography', 'spacing', 'borderRadius', 'shadows', 'elevation'];
for (const cat of categories) {
  if (tokens[cat]) {
    cssContent += `\n  /* --- ${cat.toUpperCase()} --- */\n`;
    for (const [key, val] of Object.entries(tokens[cat])) {
      const cssKey = key.replace(/\./g, '-');
      let cssVal = val;
      if (key.includes('font-family')) {
        if (typeof val === 'string' && !val.startsWith("'") && !val.startsWith('"')) {
          cssVal = `'${val}'`;
        }
      }
      cssContent += `  --${cssKey}: ${cssVal};\n`;
    }
  }
}

cssContent += `}\n\n`;

// 3. Output color roles referencing the primitive colors
// Light Theme mapping
cssContent += `/* ==========================================================================
   COLOR ROLES (LIGHT THEME)
   ========================================================================== */
:root, [data-theme="light"] {
`;
if (tokens.color && tokens.color.light) {
  for (const [role, hsl] of Object.entries(tokens.color.light)) {
    const varName = hslToVarMap[hsl];
    cssContent += `  --${role}: var(${varName});\n`;
  }
}
cssContent += `}\n\n`;

// Dark Theme mapping
cssContent += `/* ==========================================================================
   COLOR ROLES (DARK THEME)
   ========================================================================== */
[data-theme="dark"] {
`;
if (tokens.color && tokens.color.dark) {
  for (const [role, hsl] of Object.entries(tokens.color.dark)) {
    const varName = hslToVarMap[hsl];
    cssContent += `  --${role}: var(${varName});\n`;
  }
}
cssContent += `}\n\n`;

// System dark mode override support
cssContent += `/* Support system preference dark mode (if data-theme is not explicitly set to light) */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
`;
if (tokens.color && tokens.color.dark) {
  for (const [role, hsl] of Object.entries(tokens.color.dark)) {
    const varName = hslToVarMap[hsl];
    cssContent += `    --${role}: var(${varName});\n`;
  }
}
cssContent += `  }
}\n`;

// Write the compiled CSS content
try {
  fs.writeFileSync(cssPath, cssContent, 'utf8');
  console.log(`Successfully generated ${cssPath}`);
} catch (err) {
  console.error('Failed to write CSS file:', err);
  process.exit(1);
}
